//import Header from "@/components/Header";
import HeaderMobile from "@/components/HeaderMobile";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import FooterMobile from "@/components/FooterMobile";
//import FooterMobile from "@/components/FooterMobile";
// import { useMediaQuery } from "@mui/material";

const openSans = Open_Sans({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <HeaderMobile />
        {children}
        <FooterMobile />
      </body>
    </html>
  );
}
