//import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import MobileNav from "@/components/MobileNav";
import MobileFooter from "@/components/MobileFooter";
import MobileHeader from "@/components/MobileHeader";
// import { useMediaQuery } from "@mui/material";

const openSans = Open_Sans({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <MobileHeader />
        <MobileNav />
        {children}
        <MobileFooter />
      </body>
    </html>
  );
}
