import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import Header from "@/components/Header";
import Nav from "@/components/Nav";
import Banner from "@/components/Banner";
import Footer from "@/components/Footer";

import MobileHeader from "@/components/MobileHeader";
import MobileNav from "@/components/MobileNav";
import MobileFooter from "@/components/MobileFooter";

const openSans = Open_Sans({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MobileHeader />
        <MobileNav />
        <div className={`md:mx-20 lg:mx-48 xl:mx-56 font-sans`}>{children}</div>
        <MobileFooter />
      </body>
    </html>
  );
}
